name: Pebble UI Deploy

on:
  push:
    branches: [ main ]
    paths:
      - "pebbleui/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd pebbleui
          npm install

      - name: Build & Deploy
        run: |
          cd pebbleui
          npm run deploy

      - name: Deploy React build to S3
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --delete --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: pebble-frontend8712   # REAL bucket name
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-southeast-2
          SOURCE_DIR: pebbleui/build
